function [] = dataTool(varargin)
    %dataTool Helpers for files generated by NEMOH.
    % For example,
    %      dataTool 
    %      dataTool path
    %     displays the path where NEMOH run data is stored.
    %      dataTool clean
    %     will remove all NEMOH run data.

    % Get command
    if size(varargin) == 0
        command = 'path';
    else
        command = varargin{1};
    end

    % NEMOH output stored in fixed user-centric location
    WOTDataPath = WecOptLib.utils.getUserPath();
    subdirectory = [WOTDataPath filesep 'RM3_Nemoh_Runs'];

    if strcmp(command, 'path')
        disp("Path to NEMOH data files:")
        disp(subdirectory)
        return
    end
    
    if strcmp(command, 'clean')
        
        disp("Cleaning NEMOH outputs...")
        
        % Clean all NEMOH runs
        files = dir(subdirectory);
        dirFlags = [files.isdir];
        subFolders = files(dirFlags);
        
        % Print folder names to command window.
        for k = 1 : length(subFolders)
            
            if strcmp(subFolders(k).name, ".") || ...
               strcmp(subFolders(k).name, "..")
                continue
            end
            
            subFolderPath = [subdirectory filesep subFolders(k).name];
            WecOptLib.nemoh.cleanNemoh(subFolderPath);
            
        end
        
        disp("Done")

    end

end

