classdef Mesh < WecOptTool.base.Data
    
    properties (GetAccess=protected)
        meta = struct("name", {"xzSymmetric",       ...
                               "nodes",             ...
                               "panels",            ...
                               "name",              ...
                               "zG"},               ...
                      "validation", {@islogical,        ...
                                     @istable,          ...
                                     @isnumeric,        ...
                                     @ischarorstring,   ...
                                     @isnumeric});
    end
    
end

function result = ischarorstring(x)
    result = ischar(x) || isstring(x);
end
