
SPHINXBUILD     = sphinx-build
BUILDDIR        = _build
SPHINXOPTS      =

html:
    $(SPHINXBUILD) -b html $(ALLSPHINXOPTS) . $(BUILDDIR)
    @echo
    @echo "Build finished. The HTML pages are in $(BUILDDIR)."

clean:
    rm -rf $(BUILDDIR)/*
